# Generated by Django 4.0.3 on 2022-03-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('duration', models.DurationField()),
                ('auhor', models.CharField(max_length=25)),
            ],
        ),
    ]
