# Generated by Django 4.0.3 on 2022-04-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nested_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='reting',
            new_name='rating',
        ),
    ]
